### ISSUE TITLE
Unable to parse plotly doc html

### ISSUE THREAD

**Issue by rabyj** [hynek/doc2dash#143]
Tried to create plotly docsets. 

I'm getting the following when trying to run `doc2dash 3.0.0` on the [generated html](https://github.com/plotly/plotly.py/blob/master/doc/apidoc/Makefile) (made from sphinx)

~~~shell
doc2dash doc/apidoc/_build/html
"$HOME/Projects/sources/plotly.py/doc/apidoc/_build/html" does not contain a known documentation format.

doc2dash doc/apidoc/_build/html -I doc/apidoc/_build/html/index.html
Index page "doc/apidoc/_build/html/index.html" does not exist within "$HOME/Projects/sources/plotly.py/doc/apidoc/_build/html".
~~~
The index page very much exists at that location.

I really don't know if it's a plotly html or doc2dash problem, so here is the related plotly issue https://github.com/plotly/plotly.py/issues/2060. It details how I created the htlm also, if someone is brave enough to attempt to reproduce. (it's just 8 very simple commands but I use conda)

**Comment by hynek** [comment]
would you mind uploading a zip file of `doc/apidoc/_build/html` please?

**Comment by rabyj** [comment]
Here you go, thanks for the quick answer!

I also uploaded the rest of ` _build`, the `doctrees` folder, in case.

[plotly_apidoc_html.zip](https://github.com/hynek/doc2dash/files/10581446/plotly_apidoc_html.zip)
[plotly_apidoc_doctrees.zip](https://github.com/hynek/doc2dash/files/10581442/plotly_apidoc_doctrees.zip)

**Comment by hynek** [comment]
OK there is a bunch of problems with that documentation build. The main being that `objects.inv` doesn't contain a project name and a project version (both fields are empty). That makes doc2das reject it as invalid because it can't parse it:

```
# Sphinx inventory version 2
# Project:
# Version:
# The remainder of this file is compressed using zlib.
```

You can add them with an editor and doc2dash will run.

There seems tho that it has a bunch of references to symbols that don't exist under the names: you will get a lot of warnings like:

> intersphinx: path 'generated/plotly.graph_objs.waterfall.totals.marker.html' is in objects.inv, but does not exist. Skipping.

The correct path is `generated/plotly.graph_objects.waterfall.totals.marker.html` (objects, not objs) tho.

---

As for the index path: it has to be relative to the documentation – i.e. just `index.html`.

**Comment by rabyj** [comment]
Thanks a lot! Still bugging but making progress!

I have modified `objects.inv` this way
```
# Sphinx inventory version 2
# Project: plotly
# Version: 5.12.0
```

with `doc2dash doc/apidoc/_build/html`, I get a `[Errno 36] File name too long`.  It seems it reads a file path the wrong way, creating recursive files names that end up being way too long
```
Traceback (most recent call last):
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/bin/doc2dash", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/site-packages/doc2dash/__main__.py", line 197, in main
    docset = prepare_docset(
             ^^^^^^^^^^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/site-packages/doc2dash/__main__.py", line 347, in prepare_docset
    shutil.copytree(source, docs)
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/shutil.py", line 560, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/USHERBROOKE/rabj2301/miniconda3/envs/plotly_docs/lib/python3.11/shutil.py", line 514, in _copytree
    raise Error(errors)
shutil.Error: [('$HOME/Projects/sources/plotly.py/doc/apidoc/_build/html/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents', './html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents', "[Errno 36] File name too long: '$HOME/Projects/sources/plotly.py/doc/apidoc/_build/html/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents/html.docset/Contents/Resources/Documents'")]

**Comment by hynek** [comment]
uhhh… is there some sym link or something going on? Have you changed anything else?

Because for me, the following works when called from the same directory as plotly is:

```console
$ pipx run doc2dash -fI index.html plotly
```

`plotly` being `_build/html` in your case.

Wait, could it be you're accidentally trying to create the docset within the doc directory?

**Comment by rabyj** [comment]
I am trying to create the docset from the parent of `doc`, i.e. at the root of the git directory.

I tried to run it the following ways
```
cwd: $HOME/projects/sources/plotly.py
command: doc2dash doc/apidoc/_build/html

cwd: $HOME/projects/sources/plotly.py/doc/apidoc
command: doc2dash -fI index.html _build/html
```

In both cases, it creates a `html.docset` at the cwd, but since there is still a `shutil.Error` it is probably incomplete.
[html.docset.zip](https://github.com/hynek/doc2dash/files/10711239/html.docset.zip)

**Comment by hynek** [comment]
OK let's do the inverse test: please download your [html archive](https://github.com/hynek/doc2dash/files/10581446/plotly_apidoc_html.zip) and try again.

If that doesn't work, please try "pipx run doc2dash". 

None of this makes sense – the function that's failing here is `shutil.copytree` from the stdlib! 😳

**Comment by rabyj** [comment]
Good idea! Thanks!

Tried with `pipx 1.1.0`, installed on base system `Python 3.8.1` (user level)
```
cwd: $HOME/Documents/plotly_apidoc/doc/apidoc/_build #plotly_apidoc being the extracted html archive
command: pipx run doc2dash -fI index.html html/ 
Got
⚠️  doc2dash is already on your PATH and installed at
    $HOME/.local/bin/doc2dash. Downloading and running anyway.
" $HOME/Documents/plotly_apidoc/doc/apidoc/_build/html" does not contain a known documentation format.
```
Then tried many variations with and without index.htlml, from different folders, and with doc2dash installed through pipx, but nothing.

Figured maybe it was the python version.
Installed `condax` and `doc2dash (2.3.0)` through it. It installed it with `Python 3.11.0` apparently.

So now that my env is fixed, I got a more explicit error . I did not modify the objects.inv file again because it said the file was corrupted when I did that, but maybe it's the reason for the last error.
```
user@computer:~/.../doc/apidoc$ doc2dash _build/html/
Converting intersphinx docs from "html" to "./html.docset".
Parsing documentation...
Added 17,029 index entries.
Adding table of contents meta data...  [-------------------------------------------]    1%  00:07:21
Adding table of contents meta data...  [-------------------------------------------]    1%  02:41:11
  File "$HOME/.local/bin/doc2dash", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/doc2dash/__main__.py", line 232, in main
    toc.close()
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/doc2dash/parsers/utils.py", line 149, in patch_anchors
    patch_files(pbar)
  File "$HOME/.condax/doc2dash/lib/python3.11/site-packages/doc2dash/parsers/utils.py", line 130, in patch_files
    with codecs.open(full_path, mode="r", encoding="utf-8") as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 905, in open
FileNotFoundError: [Errno 2] No such file or directory: './html.docset/Contents/Resources/Documents/generated/plotly.graph_objs.html'
```

**Comment by hynek** [comment]
_blinks_

have you entertained the thought that your computer might be cursed?

***

Let’s go basic… you mention doc2dash 2.3.0… that’s ancient (and the progress bars look ancient too).

The “does not contain a known format” is the old error, no? I.e. where you have to fill in the name and version by hand.

Please do that, use pipx run again and additionally give me (if it doesn’t work):

- the version of doc2dash that you’re running
- your OS
- try to convert any other documentation so we can know whether it’s plotly or something else. You can use https://github.com/hynek/structlog which definitely works. You should be able to build the docs using `tox -e docs`

I’m leaving for vacation later today and won’t be back until March, so this is all the help I can offer for now. 😅 But please make sure objects.inv is OK and you’re running doc2dash 3.0.0.

**Comment by rabyj** [comment]
thank you so much for everything!

**Comment by hynek** [comment]
Did you… figure it out what possessed your computer?

**Comment by rabyj** [comment]
The `structlog` test worked.

I had not retried generating plotly html since the documentation generation was long, and the `objects.inv` seemed corrupted. I regenerated it, and modified the `.inv`. It ran!

Now, I'm unsure if the docset actually works since I have now found out I don't know how to truly add it to Zeal without an xml feed, but this is probably an entirely different issue if it doesn't work. I was, in fact, able to parse the plotly html doc with doc2dash, and so I think my issue is technically resolved. :)

If you have an idea about Zeal integration, please throw it my way!

-----------
Additionnal context information
- The documentation generation on the plotly side was done with `Python 3.8.16` and their requirements.txt.
- The docset generation was done with `doc2dash, version 3.0.0`, installed via `pipx 1.1.0`.

I had a bit of a problem making sure pipx used python3, for the doc2dash install, but doing the install from within a conda env with python3 worked. (similar to [this pipx question](https://stackoverflow.com/a/69828751))
