### ISSUE TITLE
raise Error but success？

### ISSUE THREAD

**Issue by hype1type** [hynek/doc2dash#151]
Hello, first of all, I am a newbie, from China, and some problems I have consulted a lot of information can not solve, maybe I can say that I don't know whether it is right or wrong!
So, ask you some questions! thank you.

I'm using Anaconda's virtual environment, windows 22H2, python 3.7， use 
`pip install doc2dash`  
`pip install sphinx_rtd_theme`

Since I can't find a suitable material to use, so it often reports errors， **does not contain a known documentation format**
when i read the article [productive-fruit-fly-programmer](https://hynek.me/articles/productive-fruit-fly-programmer/), i tried to do some. 

so i downloaded the file named **structlog**, and use it to try.
![image](https://user-images.githubusercontent.com/95662043/231515953-ec7f3276-19e9-4424-bda4-78dbca8aa22e.png)
and use this command `doc2dash -I index.html ./` and get this answer below。 Even though it reported an error, I got a file and opened it in zeal!
![image](https://user-images.githubusercontent.com/95662043/231517275-196b3b5b-1040-48fe-a959-f48c2b994128.png)

So I'm wondering if this counts as a success? And how can I output some features such as classes, attributes, functions, what command should I use, can you provide examples in the article?

```
(docset) G:\mypython_example\scripts\scrapy-master>doc2dash -I index.html ./
Traceback (most recent call last):
  File "C:\Users\wld\anaconda3\envs\docset\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\wld\anaconda3\envs\docset\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wld\anaconda3\envs\docset\Scripts\doc2dash.exe\__main__.py", line 7, in <module>
  File "C:\Users\wld\anaconda3\envs\docset\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\wld\anaconda3\envs\docset\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\wld\anaconda3\envs\docset\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\wld\anaconda3\envs\docset\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\wld\anaconda3\envs\docset\lib\site-packages\doc2dash\__main__.py", line 198, in main
    source, dest, name, index_page, enable_js, online_redirect_url
  File "C:\Users\wld\anaconda3\envs\docset\lib\site-packages\doc2dash\__main__.py", line 347, in prepare_docset
    shutil.copytree(source, docs)
  File "C:\Users\wld\anaconda3\envs\docset\lib\shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('G:\\mypython_example\\scripts\\scrapy-master\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset', '.\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset\\Contents\\Resources\\Documents\\scrapy-master.docset', "[WinError 3] 系统找不到指定的路径。: '.\\\\scrapy-master.docset\\\\Contents\\\\Resources\\\\Documents\\\\scrapy-master.docset\\\\Contents\\\\Resources\\\\Documents\\\\scrapy-master.docset\\\\Contents\\\\Resources\\\\Documents\\\\scrapy-master.docset\\\\Contents\\\\Resources\\\\Documents\\\\scrapy-master.docset'")]

```

```
Package                       Version
----------------------------- ---------
alabaster                     0.7.13
attrs                         22.2.0
Babel                         2.12.1
beautifulsoup4                4.12.2
certifi                       2022.12.7
charset-normalizer            3.1.0
click                         8.1.3
colorama                      0.4.6
coloredlogs                   15.0.1
doc2dash                      2.3.0
docutils                      0.18.1
flatbuffers                   23.3.3
humanfriendly                 10.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.3.0
Jinja2                        3.1.2
MarkupSafe                    2.1.2
onnxruntime                   1.14.1
packaging                     23.0
pip                           23.0.1
Pygments                      2.15.0
pyreadline                    2.1
pytz                          2023.3
requests                      2.28.2
setuptools                    67.6.1
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.4
Sphinx                        5.3.0
sphinx-rtd-theme              1.2.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
typing_extensions             4.5.0
urllib3                       1.26.15
wheel                         0.40.0
zipp                          3.15.0
zope.interface                6.0
```

**Comment by hype1type** [comment]
i use the command `doc2dash ./doc2dash` and `doc2dash ./structlog`!!!! get it
```
(docset) G:\mypython_example\scripts>doc2dash ./doc2dash
Converting intersphinx docs from "doc2dash" to ".\doc2dash.docset".
Parsing documentation...
Added 0 index entries.
Adding table of contents meta data...  [-------------------------------------------------------------------------]    0%Adding table of contents meta data...  [#########################################################################]  100%

(docset) G:\mypython_example\scripts>doc2dash ./structlog
Converting intersphinx docs from "structlog" to ".\structlog.docset".
Parsing documentation...
Added 206 index entries.
Adding table of contents meta data...  [-------------------------------------------------------------------------]    0%Adding table of contents meta data...  [#########################################################################]  100%
```
