### ISSUE TITLE
exception while generating docs for click

### ISSUE THREAD

**Issue by glyph** [hynek/doc2dash#58]
Please let me know if there's a workaround, I'm consulting these docs a lot :).
```console
$ doc2dash -n click-6.7 -u http://click.pocoo.org/6/ _build/dirhtml
Converting intersphinx docs from "dirhtml" to "./click-6.7.docset".
Parsing documentation...
Added 172 index entries.
Adding table of contents meta data...  [#################################]  100%
Traceback (most recent call last):
  File "/Users/glyph/.local/bin/doc2dash", line 11, in <module>
    sys.exit(main())
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/doc2dash/__main__.py", line 149, in main
    toc.close()
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/doc2dash/parsers/utils.py", line 137, in patch_anchors
    patch_files(pbar)
  File "/Users/glyph/.local/venvs/doc2dash/lib/python3.6/site-packages/doc2dash/parsers/utils.py", line 123, in patch_files
    with codecs.open(full_path, mode="r", encoding="utf-8") as fp:
  File "/Users/glyph/.local/venvs/doc2dash/bin/../lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
IsADirectoryError: [Errno 21] Is a directory: './click-6.7.docset/Contents/Resources/Documents/api/'
```

**Comment by hynek** [comment]
Wahahaha I don't care I'm on vacation without a computer. ;) Have you tried looking if there's a bug in the docs?  It used to work...I have those docs in my Dash.

**Comment by glyph** [comment]
6.7? what version?

**Comment by glyph** [comment]
(I can just try regenerating them over and over with every tag and see if it's a version issue that broke it...)

**Comment by glyph** [comment]
(Please don't respond on your vacation, this ticket will still be here when you get back.)

**Comment by glyph** [comment]
Aah. `make dirhtml` seems to be the problem.  With `make html` it builds just fine.  However, `dirhtml` is the official layout, so this breaks the `-u` option :(.

**Comment by hynek** [comment]
Ugh could this be related to the reason why RTD-builds don’t work?  I’ve never used/heard of dirhtml before so pardon my ignorance.
