### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by andyfangdz** [hynek/doc2dash#63]
When trying to convert the api for [Cozmo](https://github.com/anki/cozmo-python-sdk), the following error occured:

```
Converting intersphinx docs from "cozmo-api" to "/Users/andy/Library/Application Support/doc2dash/DocSets/cozmo-api.docset".
Parsing documentation...
Traceback (most recent call last):
  File "/Users/andy/anaconda/bin/doc2dash", line 11, in <module>
    sys.exit(main())
  File "/Users/andy/anaconda/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andy/anaconda/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/andy/anaconda/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andy/anaconda/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/andy/anaconda/lib/python3.5/site-packages/doc2dash/__main__.py", line 136, in main
    for entry in doc_parser.parse():
  File "/Users/andy/anaconda/lib/python3.5/site-packages/doc2dash/parsers/intersphinx.py", line 73, in parse
    read_inventory_v2(inv_f, "", os.path.join)
  File "/Users/andy/anaconda/lib/python3.5/site-packages/sphinx/ext/intersphinx.py", line 85, in read_inventory_v2
    raise ValueError
ValueError
Exception ignored in: <generator object patch_anchors at 0x10ed54990>
Traceback (most recent call last):
  File "/Users/andy/anaconda/lib/python3.5/site-packages/doc2dash/parsers/utils.py", line 136, in patch_anchors
    label='Adding table of contents meta data...') as pbar:
  File "/Users/andy/anaconda/lib/python3.5/site-packages/click/termui.py", line 299, in progressbar
    from ._termui_impl import ProgressBar
  File "/Users/andy/anaconda/lib/python3.5/site-packages/click/_termui_impl.py", line 522, in <module>
    import tty
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1152, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1120, in _get_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by hynek** [comment]
Given the last 6 lines, it looks like your Python or click installation is broken.  Try installing doc2dash into a fresh virtualenv.   The paths in your traceback tell me that you installed it globally.  _Never_ install anything into your global site-packages.  You may want to try pipsi as recommended in the [installation guide](https://doc2dash.readthedocs.io/en/stable/installation.html).

**Comment by andyfangdz** [comment]
Ha, the one time I don't install cli tools in pipsi...

However, after installing it in pipsi, I'm still getting the same error. I made the path to python explicit to be sure:
```
/Users/andy/.local/venvs/doc2dash/bin/python2.7 /Users/andy/.local/bin/doc2dash -A . -f
Converting intersphinx docs from "cozmo-api" to "/Users/andy/Library/Application Support/doc2dash/DocSets/cozmo-api.docset".
Parsing documentation...
Traceback (most recent call last):
  File "/Users/andy/.local/bin/doc2dash", line 11, in <module>
    sys.exit(main())
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/doc2dash/__main__.py", line 136, in main
    for entry in doc_parser.parse():
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/doc2dash/parsers/intersphinx.py", line 73, in parse
    read_inventory_v2(inv_f, "", os.path.join)
  File "/Users/andy/.local/venvs/doc2dash/lib/python2.7/site-packages/sphinx/ext/intersphinx.py", line 85, in read_inventory_v2
    raise ValueError
ValueError
Exception RuntimeError: 'sys.path must be a list of directory names' in <generator object patch_anchors at 0x10f65cc30> ignored
```
